substitutions:
  name: environment-monitor
  friendly_name: Environment Monitor

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.178.31

api:
logger:
ota:
improv_serial:
captive_portal:

# Configuration of M5 Atom Lite onboard RGB LED
light:
  - platform: esp32_rmt_led_strip
    chipset: SK6812
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    name: "Atom Lite LED"

# M5 Atom-Lite Grove port used to connect sensor, pin and sensor
# calibraation may need updating for other platforms/ sensors
sensor:
  - platform: qmp6988
    temperature:
      name: "Temperature FB QMP ESP32"
      oversampling: 4x
      id: temp_qmp
      accuracy_decimals: 1
    pressure:
      name: "Pressure FB QMP ESP32"
      id: pressure_qmp
      oversampling: 4x
      accuracy_decimals: 0
    address: 0x70
    update_interval: 60s
    iir_filter: 2x

# MQTT Setup - esphome defaults to using hostname as prefix, add
# topic_prefix: if you want something more specific.
# Staatus, sensors, light and switch are published via MQTT
mqtt:
  broker: 192.168.178.2
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password
