substitutions:
  name: environment-monitor
  friendly_name: Environment Monitor

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: esphome.web
    version: "1.0"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.178.36

# MQTT Setup - esphome defaults to using hostname as prefix, add
# topic_prefix: if you want something more specific.
# Staatus, sensors, light and switch are published via MQTT
mqtt:
  broker: 192.168.178.2
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp32.yaml@main
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

i2c:

# Configuration of M5 Atom Lite onboard RGB LED
light:
  - platform: esp32_rmt_led_strip
    chipset: SK6812
    rgb_order: GRB
    pin: 27
    num_leds: 1
    rmt_channel: 0
    name: "Atom Lite LED"

# M5 Atom-Lite Grove port used to connect sensor, pin and sensor
# calibraation may need updating for other platforms/ sensors
sensor:
  - platform: qmp6988
    temperature:
      name: "Temperature FB QMP ESP32"
      oversampling: 4x
      id: temp_qmp
      accuracy_decimals: 1
    pressure:
      name: "Pressure FB QMP ESP32"
      id: pressure_qmp
      oversampling: 4x
      accuracy_decimals: 0
    address: 0x70
    update_interval: 60s
    iir_filter: 2x
